Rdio scanner auto-populate / Better TG info for plugins
robotastic/trunk-recorder pull request #635
Opened 2022-02-09 17:02 UTC by taclane

The rdio scanner plugin has been attempting to auto-populate "Talkgroup Groups" using the variable `tg_group`.  The plugin currently is only provided the Tallkgroup ID# and Alpha Text, and cannot access other talkgroup information that may have been read in from the csv.

Complicating things, `tg_group` is presently creating downstream issues since it is a string variable assigned an integer without type conversion. This is resulting in non-printable characters and other garbage overwriting TG group assignments in Rdio-Scanner as seen below:
<img width="600" alt="Screen_Shot_2022-02-07_at_9 25 26_AM" src="https://user-images.githubusercontent.com/12748062/153117839-e0b6f267-427f-4267-b48d-802b8511faca.png">

While the simple fix is to correct the type error, or `tg_group = "";`, the optimum solution would be to let plugins have all the talkgroup data loaded from the CSV to pass on as needed.

The call .json and other plugins could benefit by retaining this data as well.

The inability for plugins to have all the TG data was noted in the following rdio-scanner issues:
https://github.com/chuot/rdio-scanner/issues/123
https://github.com/chuot/rdio-scanner/issues/115

This PR works independently of https://github.com/robotastic/trunk-recorder/pull/630.

2022-02-09 17:15 UTC, taclane commented
@chuot For your visibility since this affects the rdio-scanner plugin.

I've been running this for the last several days, and it has successfully been a way to pull TG info from the csv and automatically populate the fields in Rdio-Scanner.  ex:
```
5611,15eb,T,Conn DOT D1,District 1,Public Works,ConnDOT,1
```
to
<img width="600" alt="Screen Shot 2022-02-09 at 12 09 27 PM" src="https://user-images.githubusercontent.com/12748062/153253116-7b962dae-8971-4581-a6dd-6cc77a9c3ef0.png">

2022-02-11 04:56 UTC, aaknitt commented
I'm wondering if it would be useful to pass along the info for all patched talkgroups as well (rdio could then in theory display alpha info for everything in the patch).  

As an alternative to sending alpha tag and group info with each call, it may be possible to send all of that talkgroup info to rdio on startup using the setup_systems() function in the plugin (though .  It could then update everything in the rdio gui at once in case any of the alpha tags have changed, rather than having to wait for a call on that talkgroup to come through to get the new info.  Not sure if the rdio API would handle that as-is or not.

2022-02-11 05:43 UTC, taclane commented
While it can be done in the admin interface, I don't believe the rdio API presently has an endpoint to just upload a talkgroup.csv in bulk.

For practical reasons, I would be somewhat against pushing an entire talkgroup set by default anyway.  While the rdio interface is really nice, it can get bogged down with a large number of TGs, and it can be extremely cumbersome to use/manage when it has the full csv for a large system.  A couple hundred unnecessary buttons on the mobile app, or a seemingly-endless dropdown menu can make the user experience pretty rough.

Auto-populating talk groups as the calls come in at least guarantees that the TR instance is able to receive those TGs or rdio scanner may have recordings archived.  I am not sure the state (or future) of rdio-scanner auto-updating _existing_ TGs with updated info from TR.  At the moment, it is only supposed to work when populating new TGs, or updating TGs with empty fields such as "" or "-".

2022-02-19 14:00 UTC, robotastic requested changes
Could you break this into 2 different PRs? The first to add additional Talkgroup fields to the Call_Info struct and the second to make changes to the Rdio plugin? I can approve the call_info ones, but I would want @chuot to review the changes to Rdio plugin

2022-02-20 05:02 UTC, taclane commented
Sure!  I'll split the PR as soon as I get a free moment.  

It would be great to get some feedback from the Rdio Scanner side, but core of this is just to connect the dots from information currently in the trunk recorder talkgroup.csv to the RS API endpoint which already accepts `talkgroup`, `talkgroupLabel`, `talkgroupName`, `talkgroupGroup`, and `talkgroupTag` as inputs.

https://github.com/chuot/rdio-scanner/blob/1eebbc115432915bf7f45473fd7e3219005e4a6c/server/parsers.go#L268-L291

2022-02-20 12:54 UTC, chuot commented
@taclane Sorry for being late. It's been a crazy week and things have piled up.

First of all, I want to thank you for handling this issue. Everything looks clean and compliant with the Rdio Scanner API.

Would the new call_info structure allow us to retrieve the number of errors and spikes that were missing from v4 (issue #602)?

@robotastic Changes approved

2022-02-24 18:49 UTC, taclane commented
@robotastic It looks like chuot is okay with the changes to the plugin, but let me know if you'd still prefer I break this apart. 

@chuot This PR alone shouldn't be able to pull the spikes and error counts out of the `freq_list`.  I can look into that next and see if there's any particular reason they've been hard coded to zero in the plugins/json.

2022-02-24 18:52 UTC, chuot commented
@taclane Thanks a lot!

2022-02-26 14:34 UTC, robotastic commented
@taclane Could you check out the `tg-info` plugin? I moved it around so the string from the TG are copied into the call-info struct:
https://github.com/robotastic/trunk-recorder/tree/tg-info
I also made the same changes you had for the rdio plugin. If things look good, I will merge that branch in.

2022-02-26 15:44 UTC, taclane commented
@robotastic 
It looks like it's working great!  I deleted all the talkgroups in rdio-scanner, and with each call it's repopulating [ID, Label, Name, Group, Tag] with info straight out of the talkgroug.csv in trunk-recorder.

2022-02-26 15:54 UTC, robotastic commented
Great - I will merge that branch in! If everything looks good, then we can cancel this PR.

2022-02-26 15:56 UTC, closed without merging