improve duplicate detection for p25p2 TDMA
robotastic/trunk-recorder pull request #866
Opened 2023-11-14 15:10 UTC by taclane

Multi-site duplicate detection currently requires _both_ calls to have the same TDMA slot number, even across different systems or frequencies.  Depending on the slot assignments from the system controllers, there is only a 50% chance to correctly identify duplicate calls across TDMA networks.

Removing the line below requiring the same TDMA status and slot essentially doubles the reliability of dupe detection on these systems.

```cpp
if ((call->get_phase2_tdma() == message.phase2_tdma) && (call->get_tdma_slot() == message.tdma_slot)) {
```

2023-11-14 16:18 UTC, EricTendian requested changes

2023-11-14 16:18 UTC, EricTendian commented on trunk-recorder/main.cc
> +    // Find candidate dublicate calls with the same talkgroup and different multisite-enabled systems
```suggestion
    // Find candidate duplicate calls with the same talkgroup and different multisite-enabled systems
```
Just fixing a typo.

2023-11-14 16:30 UTC, EricTendian approved these changes

2023-11-15 00:14 UTC, taclane commented
Streamlined the console log entry per Discord feedback.

2023-11-15 03:00 UTC, merged